### ISSUE TITLE
No new release

### ISSUE THREAD

**Issue by konobi** [gagle/node-tftp#8]
Hey there,

It seems that there hasn't been a new release since the merge from chipzz... would it be possible to get a new version released to npm? We have a downstream project that requires the fix.

thanks!

-- 
Scott

**Comment by chipzz** [comment]
The reason for this is https://github.com/chipzz/forge/commit/bb378b65ed1d5fe2dde176cce3b9e547322d54fa ; I had to hack around tftp not returning the correct error code in the file not found case. Maybe it would be better to fix this in node-tftp than in forge?

**Comment by gagle** [comment]
Mmm I completely forgot to publish it to npm, sorry. Today in the afternoon (9 hours from now) I'll publish it.

**Comment by gagle** [comment]
Done.
